ValueSet: TumorMarkerTestVS
Id: mcode-tumor-marker-test-vs
Description: """Codes representing tests for tumor markers. This value set of LOINC codes is not comprehensive and can be extended. LOINC codes are preferred. Other vocabularies can be used only if the test of interest is not covered by LOINC.

FHIR implementation note: At the current time, profiles for the specific LOINC tests mentioned here do not exist."""
* ^version = "1.0.0"
* ^status = #active
* ^date = "2020-03-18T16:05:09+00:00"
* ^publisher = "HL7 International Clinical Interoperability Council"
* ^contact.name = "HL7 International Clinical Interoperability Council"
* ^contact.telecom[0].system = #url
* ^contact.telecom[=].value = "http://www.hl7.org/Special/committees/cic"
* ^contact.telecom[+].system = #email
* ^contact.telecom[=].value = "ciclist@lists.HL7.org"
* $loinc#1695-6 "5-Hydroxyindoleacetate [Mass/time] in 24 hour Urine"
* $loinc#31203-3 "5-Hydroxyindoleacetate [Mass/volume] in 24 hour Urine"
* $loinc#1692-3 "5-Hydroxyindoleacetate [Mass/volume] in Cerebral spinal fluid"
* $loinc#1693-1 "5-Hydroxyindoleacetate [Mass/volume] in Serum or Plasma"
* $loinc#1694-9 "5-Hydroxyindoleacetate [Mass/volume] in Urine"
* $loinc#72820-4 "5-Hydroxyindoleacetate [Mass/volume] in Urine by Confirmatory method"
* $loinc#14573-0 "5-Hydroxyindoleacetate [Moles/time] in 24 hour Urine"
* $loinc#25971-3 "5-Hydroxyindoleacetate [Moles/volume] in 24 hour Urine"
* $loinc#47544-2 "5-Hydroxyindoleacetate [Moles/volume] in Cerebral spinal fluid"
* $loinc#74769-1 "5-Hydroxyindoleacetate [Moles/volume] in Platelet rich plasma"
* $loinc#50149-4 "5-Hydroxyindoleacetate [Moles/volume] in Serum or Plasma"
* $loinc#15009-4 "5-Hydroxyindoleacetate [Moles/volume] in Urine"
* $loinc#12172-3 "5-Hydroxyindoleacetate [Presence] in 24 hour Urine"
* $loinc#48168-9 "5-Hydroxyindoleacetate [Presence] in Urine"
* $loinc#11145-0 "5-Hydroxyindoleacetate/​Creatinine [Mass Ratio] in Urine"
* $loinc#44909-0 "5-Hydroxyindoleacetate and Creatinine [Interpretation] in Urine"
* $loinc#10459-6 "Alpha-1-Fetoprotein Ag [Presence] in Tissue by Immune stain"
* $loinc#11207-8 "Alpha-1-Fetoprotein [Mass/volume] in Body fluid"
* $loinc#1833-3 "Alpha-1-Fetoprotein [Mass/volume] in Cerebral spinal fluid"
* $loinc#54348-8 "Alpha-1-Fetoprotein [Mass/volume] in Cord blood"
* $loinc#49761-0 "Alpha-1-Fetoprotein [Mass/volume] in Peritoneal fluid"
* $loinc#49762-8 "Alpha-1-Fetoprotein [Mass/volume] in Pleural fluid"
* $loinc#1834-1 "Alpha-1-Fetoprotein [Mass/volume] in Serum or Plasma"
* $loinc#83073-7 "Alpha-1-Fetoprotein [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#19173-4 "Alpha-1-Fetoprotein [Moles/volume] in Pleural fluid"
* $loinc#19177-5 "Alpha-1-Fetoprotein [Moles/volume] in Serum or Plasma"
* $loinc#31993-9 "Alpha-1-Fetoprotein [Presence] in Serum or Plasma"
* $loinc#44910-8 "Alpha-1-Fetoprotein [Units/volume] in Body fluid"
* $loinc#59564-5 "Alpha-1-Fetoprotein [Units/volume] in Cerebral spinal fluid"
* $loinc#19172-6 "Alpha-1-Fetoprotein [Units/volume] in Pleural fluid"
* $loinc#19176-7 "Alpha-1-Fetoprotein [Units/volume] in Serum or Plasma"
* $loinc#83072-9 "Alpha-1-Fetoprotein [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#41274-2 "Alpha-1-Fetoprotein interpretation in Serum or Plasma"
* $loinc#49246-2 "Alpha-1-Fetoprotein interpretation in Serum or Plasma Narrative"
* $loinc#49585-3 "Alpha-1-Fetoprotein multiple of the median cutoff [Multiple of the median] in Serum or Plasma"
* $loinc#53962-7 "Alpha-1-fetoprotein.tumor marker [Mass/volume] in Serum or Plasma"
* $loinc#53960-1 "Alpha-1-fetoprotein.tumor marker [Moles/volume] in Serum or Plasma"
* $loinc#53961-9 "Alpha-1-fetoprotein.tumor marker [Units/volume] in Serum or Plasma"
* $loinc#10873-8 "Beta-2-Microglobulin [Mass/time] in 24 hour Urine"
* $loinc#54356-1 "Beta-2-Microglobulin [Mass/volume] in 24 hour Urine"
* $loinc#48166-3 "Beta-2-Microglobulin [Mass/volume] in Body fluid"
* $loinc#1951-3 "Beta-2-Microglobulin [Mass/volume] in Cerebral spinal fluid"
* $loinc#49081-3 "Beta-2-Microglobulin [Mass/volume] in Dialysis fluid"
* $loinc#88711-7 "Beta-2-Microglobulin [Mass/volume] in Peritoneal dialysis fluid"
* $loinc#59217-0 "Beta-2-Microglobulin [Mass/volume] in Peritoneal fluid"
* $loinc#59218-8 "Beta-2-Microglobulin [Mass/volume] in Pleural fluid"
* $loinc#1952-1 "Beta-2-Microglobulin [Mass/volume] in Serum or Plasma"
* $loinc#87708-4 "Beta-2-Microglobulin [Mass/volume] in Serum or Plasma --post dialysis"
* $loinc#83078-6 "Beta-2-Microglobulin [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#1953-9 "Beta-2-Microglobulin [Mass/volume] in Urine"
* $loinc#83077-8 "Beta-2-Microglobulin [Mass/volume] in Urine by Immunoassay"
* $loinc#56662-0 "Beta-2-Microglobulin [Moles/time] in 24 hour Urine"
* $loinc#50824-2 "Beta-2-Microglobulin [Moles/volume] in 24 hour Urine"
* $loinc#39458-5 "Beta-2-Microglobulin [Moles/volume] in Body fluid"
* $loinc#32301-4 "Beta-2-Microglobulin [Moles/volume] in Cerebral spinal fluid"
* $loinc#14626-6 "Beta-2-Microglobulin [Moles/volume] in Serum"
* $loinc#76484-5 "Beta-2-Microglobulin [Moles/volume] in Serum or Plasma"
* $loinc#32302-2 "Beta-2-Microglobulin [Moles/volume] in Urine"
* $loinc#43919-0 "Beta-2-Microglobulin [Presence] in Cerebral spinal fluid"
* $loinc#43818-4 "Beta-2-Microglobulin [Presence] in Serum"
* $loinc#43819-2 "Beta-2-Microglobulin [Presence] in Urine"
* $loinc#83076-0 "Beta-2-Microglobulin [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#83079-4 "Beta-2-Microglobulin [Units/volume] in Urine by Immunoassay"
* $loinc#10467-9 "Beta-2-Microglobulin amyloid Ag [Presence] in Tissue by Immune stain"
* $loinc#54355-3 "Beta-2-Microglobulin in CSF/Beta-2-Microglobulin in serum"
* $loinc#56786-7 "Beta-2-Microglobulin.tumor marker [Mass/volume] in Serum"
* $loinc#2006-5 "Cancer Ag 125 [Presence] in Serum or Plasma"
* $loinc#48677-9 "Cancer Ag 125 [Presence] in Tissue by Immune stain"
* $loinc#11210-2 "Cancer Ag 125 [Units/volume] in Body fluid"
* $loinc#15156-3 "Cancer Ag 125 [Units/volume] in Body fluid by Dilution"
* $loinc#50775-6 "Cancer Ag 125 [Units/volume] in Cerebral spinal fluid"
* $loinc#68923-2 "Cancer Ag 125 [Units/volume] in Pericardial fluid"
* $loinc#59040-6 "Cancer Ag 125 [Units/volume] in Peritoneal dialysis fluid"
* $loinc#40618-1 "Cancer Ag 125 [Units/volume] in Peritoneal fluid"
* $loinc#19165-0 "Cancer Ag 125 [Units/volume] in Pleural fluid"
* $loinc#10334-1 "Cancer Ag 125 [Units/volume] in Serum or Plasma"
* $loinc#15157-1 "Cancer Ag 125 [Units/volume] in Serum or Plasma by Dilution"
* $loinc#83082-8 "Cancer Ag 125 [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#2007-3 "Cancer Ag 15-3 [Presence] in Serum or Plasma"
* $loinc#29153-4 "Cancer Ag 15-3 [Units/volume] in Body fluid"
* $loinc#50776-4 "Cancer Ag 15-3 [Units/volume] in Cerebral spinal fluid"
* $loinc#50777-2 "Cancer Ag 15-3 [Units/volume] in Pericardial fluid"
* $loinc#50778-0 "Cancer Ag 15-3 [Units/volume] in Peritoneal fluid"
* $loinc#19186-6 "Cancer Ag 15-3 [Units/volume] in Pleural fluid"
* $loinc#6875-9 "Cancer Ag 15-3 [Units/volume] in Serum or Plasma"
* $loinc#83083-6 "Cancer Ag 15-3 [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#2009-9 "Cancer Ag 19-9 [Presence] in Serum or Plasma"
* $loinc#26924-1 "Cancer Ag 19-9 [Units/volume] in Body fluid"
* $loinc#50779-8 "Cancer Ag 19-9 [Units/volume] in Cerebral spinal fluid"
* $loinc#50780-6 "Cancer Ag 19-9 [Units/volume] in Pericardial fluid"
* $loinc#50781-4 "Cancer Ag 19-9 [Units/volume] in Peritoneal fluid"
* $loinc#19163-5 "Cancer Ag 19-9 [Units/volume] in Pleural fluid"
* $loinc#24108-3 "Cancer Ag 19-9 [Units/volume] in Serum or Plasma"
* $loinc#83084-4 "Cancer Ag 19-9 [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#2012-3 "Cancer Ag 27-29 [Presence] in Serum or Plasma"
* $loinc#50782-2 "Cancer Ag 27-29 [Units/volume] in Cerebral spinal fluid"
* $loinc#19187-4 "Cancer Ag 27-29 [Units/volume] in Pleural fluid"
* $loinc#17842-6 "Cancer Ag 27-29 [Units/volume] in Serum or Plasma"
* $loinc#12515-3 "Carcinoembryonic Ag [Mass/volume] in Body fluid"
* $loinc#2037-0 "Carcinoembryonic Ag [Mass/volume] in Cerebral spinal fluid"
* $loinc#40621-5 "Carcinoembryonic Ag [Mass/volume] in Pericardial fluid"
* $loinc#40622-3 "Carcinoembryonic Ag [Mass/volume] in Peritoneal fluid"
* $loinc#19169-2 "Carcinoembryonic Ag [Mass/volume] in Pleural fluid"
* $loinc#2038-8 "Carcinoembryonic Ag [Mass/volume] in Semen"
* $loinc#2039-6 "Carcinoembryonic Ag [Mass/volume] in Serum or Plasma"
* $loinc#83085-1 "Carcinoembryonic Ag [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#19170-0 "Carcinoembryonic Ag [Moles/volume] in Pleural fluid"
* $loinc#19167-6 "Carcinoembryonic Ag [Moles/volume] in Serum or Plasma"
* $loinc#10469-5 "Carcinoembryonic Ag [Presence] in Tissue by Immune stain"
* $loinc#19168-4 "Carcinoembryonic Ag [Units/volume] in Pleural fluid"
* $loinc#10560-1 "Carcinoembryonic Ag [Units/volume] in Semen"
* $loinc#19166-8 "Carcinoembryonic Ag [Units/volume] in Serum or Plasma"
* $loinc#85337-4 "Estrogen receptor Ag [Presence] in Breast cancer specimen by Immune stain"
* $loinc#40556-3 "Estrogen receptor Ag [Presence] in Tissue by Immune stain"
* $loinc#16112-5 "Estrogen receptor [Interpretation] in Tissue"
* $loinc#14130-9 "Estrogen receptor [Moles/mass] in Tissue"
* $loinc#85310-1 "Estrogen receptor fluorescence intensity [Type] in Breast cancer specimen by Immune stain"
* $loinc#10480-2 "Estrogen+Progesterone receptor Ag [Presence] in Tissue by Immune stain"
* $loinc#48676-1 "HER2 [Interpretation] in Tissue"
* $loinc#32996-1 "HER2 [Mass/volume] in Serum"
* $loinc#42914-2 "HER2 [Mass/volume] in Serum by Immunoassay"
* $loinc#85318-4 "HER2 [Presence] in Breast cancer specimen by FISH"
* $loinc#85319-2 "HER2 [Presence] in Breast cancer specimen by Immune stain"
* $loinc#51981-9 "HER2 [Presence] in Serum by Immunoassay"
* $loinc#31150-6 "HER2 [Presence] in Tissue by FISH"
* $loinc#72383-3 "HER2 [Presence] in Tissue by Immunoassay"
* $loinc#72382-5 "HER2 [Units/volume] in Tissue by Immunoassay"
* $loinc#18474-7 "HER2 Ag [Presence] in Tissue by Immune stain"
* $loinc#49683-6 "HER2 gene copy number/Chromosome 17 copy number in Tissue by FISH"
* $loinc#74860-8 "HER2 gene copy number/nucleus in Tissue by FISH"
* $loinc#74885-5 "HER2 panel - Tissue by FISH"
* $loinc#83054-7 "PD-L1 by clone 22C3 [Interpretation] in Tissue by Immune stain Narrative"
* $loinc#83052-1 "PD-L1 by clone 22C3 [Presence] in Tissue by Immune stain"
* $loinc#83056-2 "PD-L1 by clone 28-8 [Interpretation] in Tissue by Immune stain Narrative"
* $loinc#83055-4 "PD-L1 by clone 28-8 [Presence] in Tissue by Immune stain"
* $loinc#83057-0 "PD-L1 by clone SP142 [Presence] in Tissue by Immune stain"
* $loinc#83053-9 "Cells.programmed cell death ligand 1/100 viable tumor cells in Tissue by Immune stain. (source: LOINC)"
* $loinc#85339-0 "Progesterone receptor Ag [Presence] in Breast cancer specimen by Immune stain"
* $loinc#40557-1 "Progesterone receptor Ag [Presence] in Tissue by Immune stain"
* $loinc#16113-3 "Progesterone receptor [Interpretation] in Tissue"
* $loinc#10861-3 "Progesterone receptor [Mass/mass] in Tissue"
* $loinc#31207-4 "Progesterone receptor [Moles/mass] in Tissue"
* $loinc#85331-7 "Progesterone receptor fluorescence intensity [Type] in Breast cancer specimen by Immune stain"
* $loinc#47738-0 "Prostate specific Ag [Mass/volume] in Body fluid"
* $loinc#59230-3 "Prostate specific Ag [Mass/volume] in Cerebral spinal fluid"
* $loinc#59223-8 "Prostate specific Ag [Mass/volume] in Peritoneal fluid"
* $loinc#59221-2 "Prostate specific Ag [Mass/volume] in Pleural fluid"
* $loinc#19199-9 "Prostate specific Ag [Mass/volume] in Semen"
* $loinc#2857-1 "Prostate specific Ag [Mass/volume] in Serum or Plasma"
* $loinc#35741-8 "Prostate specific Ag [Mass/volume] in Serum or Plasma by Detection limit <= 0.01 ng/mL"
* $loinc#83112-3 "Prostate specific Ag [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#34611-4 "Prostate specific Ag [Mass/volume] in Urine"
* $loinc#19200-5 "Prostate specific Ag [Moles/volume] in Semen"
* $loinc#19197-3 "Prostate specific Ag [Moles/volume] in Serum or Plasma"
* $loinc#10508-0 "Prostate specific Ag [Presence] in Tissue by Immune stain"
* $loinc#19198-1 "Prostate specific Ag [Units/volume] in Semen"
* $loinc#19195-7 "Prostate specific Ag [Units/volume] in Serum or Plasma"
* $loinc#15325-4 "Prostate specific Ag/Prostate volume calculated"
* $loinc#15323-9 "Prostate specific Ag/Prostate volume calculated from height, width and length"
* $loinc#15324-7 "Prostate specific Ag/Prostate volume calculated from planimetry"